In [2]:
import os
import pandas as pd
from glob import glob
from tqdm import tqdm
from tqdm.contrib import tzip

WD = 'C:\\Users\Sunwoo\Desktop\업무\code\[코드스테이츠] AIB16\AI_16_허선우_Section2_Project\Data'
os.chdir(WD)

In [2]:
region = pd.Series(sorted(glob("데이터/*.xlsx"))).str.split('_').str[-1].str.split('.').str[0].to_list()

def make_dataset(wd, region):
    
    wd_list = sorted(glob(wd))
    df = pd.DataFrame()
    
    for fn, re in zip(wd_list, region):
        
        df_new = pd.read_excel(fn, index_col = 0)
        df_new['region'] = re
        df = pd.concat([df, df_new])
        
    return df

dataset_info = make_dataset(wd = "데이터/*.xlsx", region=region)
dataset_info.to_csv('dataset_info.csv')

pd.read_csv('dataset_info.csv')

,통신판매번호,신고기관명,상호,사업자등록번호,법인여부,대표자명,전화번호,전자우편,신고일자,사업장소재지,사업장소재지(도로명),업소상태,신고기관 대표연락처,판매방식,취급품목,인터넷도메인,호스트서버소재지,region
0,2022-세종-0125,세종특별자치시,하루스토어,106-25-16268,개인,김지영,010-5099-****,h97**@naver.com,2022-02-25 00:00:00,세종특별자치시 나성동 ***********,세종특별자치시 나성북**로 ****** 디펠리체 **층 ************호 *...,통신판매업 신고,NaN,인터넷,종합몰,쿠팡,NaN,세종특별자치시
1,2022-세종-0126,세종특별자치시,디스오트,509-38-00868,개인,오다슬,010-2370-****,ods05**@naver.com,2022-02-25 00:00:00,세종특별자치시 보람동 ****** 호려울마*****,세종특별자치시 시청대로 ****** ******동 ********호 (보람동** 호...,통신판매업 신고,NaN,인터넷,의류/패션/잡화/뷰티,네이버 스마트 스토어,NaN,세종특별자치시
2,2022-세종-0124,세종특별자치시,오늘산책,255-23-01194,개인,박미정,010-6677-****,flg**@naver.com,2022-02-25 00:00:00,세종특별자치시 해밀동 산 ** 해밀마을******,세종특별자치시 해밀**로 ****** ******동 ******호 (해밀동** 해밀...,통신판매업 신고,NaN,인터넷,기타,네이버 스마트 스토어,NaN,세종특별자치시
3,2022-세종아름-0082,세종특별자치시,에제에제,472-75-00289,개인,강은비,010 - 2339 - ****,wsj**@naver.com,2022-02-25 00:00:00,세종특별자치시 아름동 ******** 범지기마을******,세종특별자치시 달빛로 ******** ********동 ********호 (아름동*...,통신판매업 신고,NaN,인터넷,의류/패션/잡화/뷰티,네이버 스마트 스토어,NaN,세종특별자치시
4,2022-세종아름-0080,세종특별자치시,엘엔샵,788-23-01210,개인,이상래,010 - 4833 - ****,ln-shop78**@naver.com,2022-02-25 00:00:00,세종특별자치시 고운동 ******** 가락마을******,세종특별자치시 마음로 ******** ********동 ******호 (고운동** ...,통신판매업 신고,NaN,인터넷,건강/식품,11번가,NaN,세종특별자치시
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1741942,2002-00004,제주특별자치도 서귀포시,제주물류닷컴,616-91-22525,개인,NaN,064 763 6565,NaN,2002-08-19 00:00:00,서귀동 ************,제주특별자치도 서귀포시 일주동로 ******** *****,통신판매업 신고,064-760-2623,인터넷,건강/식품,www.jejumullyu.com,서귀동 283-16,제주특별자치도
1741943,2002-서귀중앙-0001,제주특별자치도 서귀포시,제주물류닷컴,NaN,개인,양남희,763-6565,nh65**@jejumullyu.com,2002-08-19 00:00:00,제주특별자치도 서귀포시 서귀동 ******번지 *****,제주특별자치도 서귀포시 일주동로 ******** *****,통신판매업 신고,064-760-2623,인터넷,건강/식품,www.jejumullyu.com,NaN,제주특별자치도
1741944,2002-00002,제주특별자치도 서귀포시,호텔굿인,616-81-35619,법인,NaN,NaN,NaN,2002-01-01 00:00:00,NaN,NaN,통신판매업 폐업,064-760-2623,인터넷,건강/식품,www.goodinn.co.kr,서귀포시 서귀동 411-13,제주특별자치도
1741945,2006-00020,제주특별자치도 서귀포시,우리농원,616-92-10123,개인,고병주,064 764 2100,namch**@gmail.net,07.0-2.-01,제주도 서귀포시 남원읍 태흥리 ************,NaN,통신판매업 신고,064-760-2623,인터넷,기타,www.woorihalla.com,제주도 서귀포시 남원읍 태흥리 1249-1,제주특별자치도
1741946,2005-00027,제주특별자치도 서귀포시,부흥농장,616-91-75153,개인,김영진,064 733 3111,somt**@hanmail.net,05.0-5.-16,제주도 서귀포시 남원읍 신*****,NaN,통신판매업 휴업,064-760-2623,인터넷,기타,www.bluedragon.co.kr,제주도 서귀포시 남원읍 신례리 4,제주특별자치도

In [3]:
dataset_info = pd.read_csv('dataset_info.csv')
infodata = dataset_info.query('사업자등록번호 == 사업자등록번호' and '업소상태 == 업소상태')[['사업자등록번호', '법인여부', 'region', '업소상태',  '판매방식', '취급품목']]
infodata.drop_duplicates(inplace = True)
infodata.reset_index(inplace = True, drop = True)

In [4]:
#취급 품목 추가
item_1 = pd.get_dummies(infodata['취급품목'].str.split('/ ').str[0])
item_2 = pd.get_dummies(infodata['취급품목'].str.split('/ ').str[1])

item_table = (item_1 + item_2).drop(columns = ['null', '기타'])
item_table['기타'] = (item_table.sum(axis=1) == 0).astype('int')

infodata = pd.concat([infodata, item_table], axis = 1)
infodata = infodata.iloc[infodata['사업자등록번호'].drop_duplicates().index].reset_index(drop=True)
infodata.drop(columns =['취급품목'], inplace = True)

# 판매방식
channel_1 = pd.get_dummies(infodata['판매방식'].str.split('/ ').str[0])
channel_2 = pd.get_dummies(infodata['판매방식'].str.split('/ ').str[1])

channel_table = (channel_1 + channel_2)

infodata = pd.concat([infodata, channel_table], axis = 1)
infodata.drop(columns =['판매방식', '법인여부'], inplace = True)

# 업소상태
rep_dict = {
    '통신판매업 신고': 1,
    '영업재개':1, 
    '통신판매업 폐업':0, 
    '통신판매업 휴업':0, 
    '직권말소' : 0, 
    '직권취소' : 0,
    '타시군구전입' : 1}
infodata['업소상태'] = infodata['업소상태'].replace(rep_dict)



# 수도권 여부
infodata['수도권여부'] = \
                    ((infodata['region'] == '서울특별시').astype('int') + \
                    (infodata['region'] == '경기도').astype('int') + \
                    (infodata['region'] == '인천광역시').astype('int'))
infodata.drop(columns =['region'], inplace = True)

In [5]:
infodata

,사업자등록번호,업소상태,가구/수납용품,가전,건강/식품,교육/도서/완구/오락,레저/여행/공연,상품권,성인/성인용품,의류/패션/잡화/뷰티,자동차/자동차용품,종합몰,컴퓨터/사무용품,기타,TV홈쇼핑,기타,신문잡지,인터넷,카탈로그,수도권여부
0,106-25-16268,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0
1,509-38-00868,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
2,255-23-01194,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
3,472-75-00289,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
4,788-23-01210,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1619362,616-18-97488,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1619363,616-90-43805,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
1619364,616-91-25823,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1619365,616-91-22525,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1619366,616-81-35619,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0

In [ ]:
infodata.to_csv('infodata.csv')

In [14]:
infodata = pd.read_csv('infodata.csv', index_col = 0)
infodata.rename(columns={'기타':'기타_판매품목', '기타.1':'기타_판매방식'}, inplace = True)

infodata

,사업자등록번호,업소상태,가구/수납용품,가전,건강/식품,교육/도서/완구/오락,레저/여행/공연,상품권,성인/성인용품,의류/패션/잡화/뷰티,자동차/자동차용품,종합몰,컴퓨터/사무용품,기타_판매품목,TV홈쇼핑,기타_판매방식,신문잡지,인터넷,카탈로그,수도권여부
0,106-25-16268,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0
1,509-38-00868,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
2,255-23-01194,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
3,472-75-00289,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
4,788-23-01210,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1619362,616-18-97488,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1619363,616-90-43805,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
1619364,616-91-25823,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1619365,616-91-22525,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1619366,616-81-35619,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0

In [15]:
infodata.to_csv('infodata.csv')